import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from 'react-redux';
import store from "../store/store"
import App from "./app.js"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <App>
        <body className={inter.className}>{children}</body>
      </App>
    </html>
  );
}
